DROP TABLE IF EXISTS deletedUsers;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(254) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(5) NOT NULL DEFAULT 'USER' CHECK (role IN ('USER', 'ADMIN')),
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE deletedUsers (
    id SERIAL PRIMARY KEY,
    email VARCHAR(254) NOT NULL,
    deletedBy INTEGER NOT NULL, 
    deletedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
